name: Python FastAPI App CI/CD

on:
  push:
    paths:
      - "03-real-apps/python-app/**"
    branches: [main, develop]
  pull_request:
    paths:
      - "03-real-apps/python-app/**"
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  APP_PATH: "03-real-apps/python-app"
  IMAGE_NAME: fastapi-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        working-directory: ${{ env.APP_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        working-directory: ${{ env.APP_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ${{ env.APP_PATH }}
        run: pytest

    dockerhub:
      needs: test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push to Docker Hub
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest ./04-docker
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
